### PR TITLE
Fix to use `.Sent` folder to be default sent mail directory

### PR DESCRIPTION
**Pull request by iliajie**

### CODE REVIEW

**Comment by jcameron** [comment]
Won't this break the sent folder for existing users who haven't set a custom folder name?

**Comment by iliajie** [comment]
That actually would, you're tight!

Then probably better to do it with the config change, so it would only affect a new installs?

**Comment by iliajie** [comment]
The motivation is to keep things consistent with what's  generally expected by mail clients and by IMAP, i.e. Dovecot by default is configure to use `.Sent` folder.

**Comment by jcameron** [comment]
Is this something Dovecot controls, or the mail client?

**Comment by iliajie** [comment]
> Is this something Dovecot controls, or the mail client?

I think both, actually. But if I remember correctly off hand Dovecot is configured to decide where to store outgoing mail by default.

**Comment by jcameron** [comment]
How does Dovecot even access outgoing email though? I'd expect it goes via SMTP ..

**Pull request closed without merging**
