### PR TITLE
Fix to list folders Location in IMAP too

### PR DESCRIPTION
**Pull request by iliajie**
Ref.: https://github.com/virtualmin/Virtualmin-Config/commit/b5c94dfc6671d47ffd569a3a843a0763f2d9af97#commitcomment-127478551

### CODE REVIEW

**Comment by jcameron** [comment]
I don't think we want this ... in IMAP mode, the server-side folder path should never be shown.

**Comment by iliajie** [comment]
> I don't think we want this ... in IMAP mode, the server-side folder path should never be shown.

Perhaps, then it should only be shown for the user which has a shell access and/or File Manager access, to make it easier to do backups and have clearer understanding about where mail actually is?

**Comment by jcameron** [comment]
Maybe, but I feel like 99% of users don't need to see the mail folder path, and in a lot of cases it will be really long and would take up a lot of space in the table.

**Comment by iliajie** [comment]
Alright, this is definitely not that important.

**Pull request closed without merging**
