### PR TITLE
Convert German Translation to UTF-8 like authentic-theme

### PR DESCRIPTION
**Pull request by gnadelwartz**
See upcoming webmin PR for more Information.

do only merge if upcoming webmin PR is merged also!

### CODE REVIEW

**Comment by rostovtsev** [comment]
Key, thanks a lot.

**Comment by rostovtsev** [comment]
Kay, thanks a lot.

**Comment by gnadelwartz** [comment]
@rostovtsev  wasn't there also a conversation Scripts only PR?

**Comment by gnadelwartz** [comment]
ah, this is usermin!

**Comment by rostovtsev** [comment]
Kay, wait. It's incorrect. I though we discussed it with you - _**.UTF8**_ files are generated by Webmin upon setup process. There is no place for  _**.UTF8**_ files on the repo. I missed it while checking the commit.

I will have to unroll it.

**Pull request merged**
