### PR TITLE
update or create all de.UTF-8 languange strings

### PR DESCRIPTION
**Pull request by gnadelwartz**
while translation autehntic-theme I noticed that a mix of german, english and german with bad characters is display when you switch languages.

after some investigation on how authetic-theme and webmin7usermin handels translations I decided to have all german translations in de and de.UTF-8 versions.

here is the first bulk of Udates, now my users have all modules and authenitc-theme with correct german transaltions :-)

### CODE REVIEW

**Comment by jcameron** [comment]
Thanks for the patch ... but according to github, there are also diffs in the lines for other languages in the `module.info` files. Perhaps the encoding was changed?

**Comment by gnadelwartz** [comment]
Hm, I noticed this, but in diff I cant see any difference. So I suspect this has something to do with rearranging the lines, whitch I had done.

But If you ask it this way: there was sometimes a Message changing "encoding from IS0-8891-1 to UTF-8" but I ignored this because they should be nearly the same, or not?

**Comment by gnadelwartz** [comment]
I checked this on command line, and yes it the encodings of the file is changed and non latin characters are encoded different :-(, even they are shown the same in github.

can we fix this in an easy way?

**Comment by gnadelwartz** [comment]
recode -f utf-8..iso-8859-1 simply removes multi-byte characters :-(

any other ideas?

**Comment by gnadelwartz** [comment]
HA! found it :-)

`recode -v  Windows-1252..iso-8859-1 module.info`

does the trick, at least the translation of the result in google seems to be correct:

`Blokov�n� web adres���` will be converted to `Blokování web adresáøù`
and goolgle translates this to `Block web directories`

**Comment by gnadelwartz** [comment]
but again only for latin laguages :-( the problem here seems to be we have mixed different languages in one file. may be should at least seperate between latin and non-latin charset

**Comment by jcameron** [comment]
Yeah, having difference character sets in one file is the trigger. What did you use to originally edit the file?

**Comment by gnadelwartz** [comment]
I use github online editor for translation because my editors under linux and windows are not so good for displaying different encodings. github seems to be better in this case but changed encoding without a chance to revert.

If nothing else fix the problem I`ll redo the changes

**Comment by jcameron** [comment]
I have a tool that can do a smart merge of these files - if you just attach a tar.gz of your changed files to this commit thread, I will use it to extract your `de` changes and apply them.

**Comment by gnadelwartz** [comment]
only module.info files or every file i canged? I'll make to archives 😁

**Comment by gnadelwartz** [comment]
[module.info.zip](https://github.com/webmin/usermin/files/1007411/module.info.zip)

**Comment by gnadelwartz** [comment]
BTW: I missed module motd in my local usermin installation, no more there?

**Comment by jcameron** [comment]
Only the module.info files. Can you submit the other files via a regular pull request?

**Comment by gnadelwartz** [comment]
saw you updated desc_de but not included longdesc_de, any reason why not?
authentic shows longdesc on main page and it would be nice to have them also in german.

similar question about de*UTF-8 strings, I guess not needed because of upcoming changes for translation. here is problem with authentic if I display de.utf-8 lang authentic displays english desc as fallback not desc_ de.

is this a webmin or an authentic issue?

**Comment by qooob** [comment]
Because, if you have _UTF-8_ set in Webmin Configuration, it will need `.utf-8` like files, or it will fall back. Everything seems correct for me but very confusing, I agree.

**Comment by gnadelwartz** [comment]
This is clear, ab we have this fioles, BUT in module Info its the same. If there is, as currentyl, only desc_de but no desc_de.UTF-8 lines, same will happen.

This was why I'm asking why JC only the `desc_de` but not `longdesc_de `and the` UTF-8` strings from upload, i.e.:

`desc_de=Benutzerdefiniert Befehle`

was included, but not
 
```
longdesc_de=Benuterdefinierte Befehle f&#252;r Usermin anlegen, verwalten und ausf&#252;hren.
desc_de.UTF-8=Benutzerdefiniert Befehle 
longdesc_de.UTF-8=Benuterdefinierte Befehle für Usermin anlegen, verwalten und ausführen.
```

**Comment by qooob** [comment]
In my opinion - all of this ambiguousness should go.

**Comment by gnadelwartz** [comment]
Agree

**Pull request closed without merging**
